name: Deploy to surge

on:
  push:
    branches:
      - 'main'

jobs:
  deploy-to-surge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: npm install --global surge
      - run: surge ./jukify jukify.reidreininger.com --token ${{ secrets.SURGE_TOKEN }}

